<?php

namespace AppBundle\Repository;

/**
 * BuildingBaseIncomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingBaseIncomeRepository extends \Doctrine\ORM\EntityRepository
{
}
