<?php

namespace AppBundle\Repository;

/**
 * PlatformResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatformResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
