<?php

namespace AppBundle\Repository;

/**
 * PlatformBuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatformBuildingRepository extends \Doctrine\ORM\EntityRepository
{
}
